### ISSUE TITLE
Create Our Story under About

### ISSUE THREAD

**Issue by yashanand1910** [yashanand1910/entrejourn.in#27]

**Comment by Rubina110622** [comment]
1. Slides can be used as **video** OR to be used as slides that auto play on the Homepage after the first blue block (Whatever looks nice); could use effects like fade in/out
2. Pls ensure the images do not break or pixelate
3. Provided the video on the drive too and shared the link below
4. Pls let me know if you need anything else


https://www.canva.com/design/DAFEcDuUcJU/epzt_KwXyHGu2K0ULOdjcw/edit?utm_content=DAFEcDuUcJU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Rubina110622** [comment]
1. Reduce the speed of the clip
2. Have the text 'Our Story' on the left corner or the centre of the Homepage. I prefer left side since most of the headings are on the left.
3. Remove the section below 'Our Story" - the "Journeys of Mental wellbeing of Entrepreneurs"

**PLS KEEP THIS ON HOLD FOR NOW**

**Comment by yashanand1910** [comment]
@Rubina110622  I have implemented the changes including following as mentioned on WhatsApp:

> Say we have it in these order -
> 1. Towards...
> 2. Explore videos that can be renamed as Featured videos
> 3. Our Story
> 4. Our Mission
> 5. Wish to Support..
> 6. Our latest...
> 7. Footer
